version: "3"
services:
  panda_webserver:
    image: nginx:latest
    volumes:
      - ./containers/nginx/default.conf.https:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
      - "80:80"
      - "8888:8888"
    command: nginx -g 'daemon off;'
    logging:
      driver: none
    depends_on:
      - panda_front

  panda_front:
    image: node:18.6
    working_dir: /usr/src/app
    ports:
      - "9025:3000"
#    expose:
#      - "9025"
    volumes:
      - ./packages/front/panda_front/:/usr/src/app/
    command: bash -c "yarn start"

